export { default as Navbar } from './navbar/Navbar';
export { default as Header } from './header/Header';
export { default as Join } from './join/Join';
export { default as About } from './about/About';
export { default as Meetings } from './meetings/Meetings';
export { default as Events } from './events/Events';
export { default as Team } from './team/Team';
export { default as Contact } from './contact/Contact';
export { default as Footer } from './footer/Footer';